-- "Le Fil": a French news site with subscriptions, as a development dataset.
-- The same tables as mysql/schema.sql, in PostgreSQL's own types: an ENUM column is an enum type, a
-- BOOLEAN is a boolean, an UNSIGNED integer takes the next size up, ON UPDATE CURRENT_TIMESTAMP is a trigger.

DROP TABLE IF EXISTS
  envoi_newsletter, inscription_newsletter, newsletter, lecture, favori, signalement_commentaire,
  commentaire, remboursement, paiement, moyen_paiement, abonnement, code_promo, formule_abonnement,
  utilisateur, article_revision, article_media, article_tag, tag, media, article, dossier, categorie,
  auteur
CASCADE;
DROP TYPE IF EXISTS
  auteur_genre, auteur_role, media_type, media_licence, article_statut, article_acces,
  utilisateur_statut, formule_periodicite, moyen_paiement_type, moyen_paiement_reseau,
  abonnement_statut, paiement_statut, remboursement_motif, commentaire_statut, signalement_motif,
  signalement_decision, lecture_source, lecture_appareil, newsletter_periodicite,
  inscription_origine;
DROP FUNCTION IF EXISTS touch_modifie_le();

CREATE TYPE auteur_genre AS ENUM ('male', 'female', 'other');
CREATE TYPE auteur_role AS ENUM ('redacteur', 'pigiste', 'redacteur_chef', 'correspondant', 'photographe', 'stagiaire');
CREATE TYPE media_type AS ENUM ('photo', 'illustration', 'infographie', 'video');
CREATE TYPE media_licence AS ENUM ('maison', 'agence', 'creative_commons', 'droits_reserves');
CREATE TYPE article_statut AS ENUM ('brouillon', 'relecture', 'programme', 'publie', 'archive');
CREATE TYPE article_acces AS ENUM ('libre', 'inscrit', 'abonne');
CREATE TYPE utilisateur_statut AS ENUM ('actif', 'inactif', 'suspendu', 'supprime');
CREATE TYPE formule_periodicite AS ENUM ('mensuel', 'annuel');
CREATE TYPE moyen_paiement_type AS ENUM ('carte', 'prelevement', 'paypal');
CREATE TYPE moyen_paiement_reseau AS ENUM ('visa', 'mastercard', 'amex', 'cb');
CREATE TYPE abonnement_statut AS ENUM ('essai', 'actif', 'impaye', 'suspendu', 'resilie');
CREATE TYPE paiement_statut AS ENUM ('en_attente', 'reussi', 'refuse', 'rembourse');
CREATE TYPE remboursement_motif AS ENUM ('doublon', 'erreur_facturation', 'geste_commercial', 'retractation');
CREATE TYPE commentaire_statut AS ENUM ('en_attente', 'publie', 'masque', 'supprime');
CREATE TYPE signalement_motif AS ENUM ('injure', 'hors_sujet', 'spam', 'desinformation', 'harcelement');
CREATE TYPE signalement_decision AS ENUM ('conserve', 'masque', 'supprime');
CREATE TYPE lecture_source AS ENUM ('accueil', 'rubrique', 'recherche', 'newsletter', 'reseaux', 'moteur', 'notification');
CREATE TYPE lecture_appareil AS ENUM ('ordinateur', 'mobile', 'tablette');
CREATE TYPE newsletter_periodicite AS ENUM ('quotidienne', 'hebdomadaire', 'mensuelle');
CREATE TYPE inscription_origine AS ENUM ('inscription', 'popup', 'pied_de_page', 'offre');

CREATE TABLE auteur (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom varchar(80) NOT NULL,
  prenom varchar(60),
  genre auteur_genre,
  initiale varchar(1) GENERATED ALWAYS AS (left(nom, 1)) STORED,
  email varchar(120),
  role auteur_role NOT NULL DEFAULT 'redacteur',
  service varchar(40),
  biographie text,
  ville varchar(60),
  arrive_le date,
  parti_le date,
  actif boolean NOT NULL DEFAULT true,
  compte_x varchar(40),
  CONSTRAINT uniq_auteur_email UNIQUE (email)
);
COMMENT ON COLUMN auteur.service IS 'Rubrique de rattachement';
COMMENT ON COLUMN auteur.parti_le IS 'NULL tant que la personne est en poste';

CREATE TABLE categorie (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id integer,
  nom varchar(60) NOT NULL,
  slug varchar(60) NOT NULL,
  description varchar(255),
  couleur char(7) NOT NULL DEFAULT '#3b6ea5',
  ordre smallint NOT NULL DEFAULT 0,
  CONSTRAINT uniq_categorie_slug UNIQUE (slug),
  CONSTRAINT fk_categorie_parent FOREIGN KEY (parent_id) REFERENCES categorie (id)
);
COMMENT ON COLUMN categorie.couleur IS 'Couleur de la rubrique en une';

CREATE TABLE dossier (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titre varchar(120) NOT NULL,
  slug varchar(120) NOT NULL,
  description text,
  ouvert_le date NOT NULL,
  clos_le date,
  en_une boolean NOT NULL DEFAULT false,
  CONSTRAINT uniq_dossier_slug UNIQUE (slug)
);

CREATE TABLE media (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom_fichier varchar(140) NOT NULL,
  type media_type NOT NULL DEFAULT 'photo',
  legende varchar(255),
  texte_alternatif varchar(255),
  credit varchar(80),
  licence media_licence NOT NULL DEFAULT 'maison',
  largeur integer,
  hauteur integer,
  poids_octets bigint,
  auteur_id integer,
  importe_le timestamp NOT NULL,
  CONSTRAINT uniq_media_fichier UNIQUE (nom_fichier),
  CONSTRAINT fk_media_auteur FOREIGN KEY (auteur_id) REFERENCES auteur (id)
);

CREATE TABLE article (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titre varchar(120) NOT NULL,
  slug varchar(160) NOT NULL,
  chapo varchar(400),
  contenu text,
  statut article_statut NOT NULL DEFAULT 'brouillon',
  acces article_acces NOT NULL DEFAULT 'libre',
  vues integer DEFAULT 0,
  publie_le timestamp,
  modifie_le timestamptz NOT NULL DEFAULT now(),
  auteur_id integer,
  categorie_id integer,
  dossier_id integer,
  media_une_id integer,
  en_une boolean NOT NULL DEFAULT false,
  temps_lecture smallint,
  nombre_mots integer,
  note_moyenne numeric(3, 2),
  metadonnees jsonb,
  CONSTRAINT uniq_article_slug UNIQUE (slug),
  CONSTRAINT fk_article_auteur FOREIGN KEY (auteur_id) REFERENCES auteur (id),
  CONSTRAINT fk_article_categorie FOREIGN KEY (categorie_id) REFERENCES categorie (id),
  CONSTRAINT fk_article_dossier FOREIGN KEY (dossier_id) REFERENCES dossier (id),
  CONSTRAINT fk_article_media_une FOREIGN KEY (media_une_id) REFERENCES media (id)
);
CREATE INDEX idx_article_auteur ON article (auteur_id);
CREATE INDEX idx_article_publication ON article (statut, publie_le);
COMMENT ON COLUMN article.titre IS 'Titre affiché en une';
COMMENT ON COLUMN article.chapo IS 'Résumé affiché sous le titre';
COMMENT ON COLUMN article.acces IS 'Niveau requis pour lire l''article en entier';
COMMENT ON COLUMN article.vues IS 'Compteur de vues, remis à zéro chaque mois';
COMMENT ON COLUMN article.temps_lecture IS 'Minutes';
COMMENT ON COLUMN article.metadonnees IS 'Balises pour les réseaux sociaux';

-- MySQL's ON UPDATE CURRENT_TIMESTAMP
CREATE FUNCTION touch_modifie_le() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.modifie_le := now();
  RETURN NEW;
END;
$$;
CREATE TRIGGER article_touch_modifie_le BEFORE UPDATE ON article
  FOR EACH ROW EXECUTE FUNCTION touch_modifie_le();

CREATE TABLE tag (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom varchar(60) NOT NULL,
  slug varchar(60) NOT NULL,
  usages integer NOT NULL DEFAULT 0,
  CONSTRAINT uniq_tag_slug UNIQUE (slug)
);
COMMENT ON COLUMN tag.usages IS 'Dénormalisé, recalculé chaque nuit';

CREATE TABLE article_tag (
  article_id integer NOT NULL,
  tag_id integer NOT NULL,
  pose_le timestamp NOT NULL,
  PRIMARY KEY (article_id, tag_id),
  CONSTRAINT fk_article_tag_article FOREIGN KEY (article_id) REFERENCES article (id) ON DELETE CASCADE,
  CONSTRAINT fk_article_tag_tag FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE
);
CREATE INDEX idx_article_tag_tag ON article_tag (tag_id);

CREATE TABLE article_media (
  article_id integer NOT NULL,
  media_id integer NOT NULL,
  position smallint NOT NULL DEFAULT 1,
  legende_specifique varchar(255),
  PRIMARY KEY (article_id, media_id),
  CONSTRAINT fk_article_media_article FOREIGN KEY (article_id) REFERENCES article (id) ON DELETE CASCADE,
  CONSTRAINT fk_article_media_media FOREIGN KEY (media_id) REFERENCES media (id)
);
CREATE INDEX idx_article_media_media ON article_media (media_id);

CREATE TABLE article_revision (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article_id integer NOT NULL,
  numero integer NOT NULL,
  auteur_id integer,
  titre varchar(120) NOT NULL,
  contenu text,
  resume_modification varchar(255),
  enregistre_le timestamp NOT NULL,
  CONSTRAINT uniq_revision UNIQUE (article_id, numero),
  CONSTRAINT fk_revision_article FOREIGN KEY (article_id) REFERENCES article (id) ON DELETE CASCADE,
  CONSTRAINT fk_revision_auteur FOREIGN KEY (auteur_id) REFERENCES auteur (id)
);

CREATE TABLE utilisateur (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar(160) NOT NULL,
  prenom varchar(60) NOT NULL,
  nom varchar(80) NOT NULL,
  pseudo varchar(40),
  ville varchar(60),
  code_postal char(5),
  pays char(2) NOT NULL DEFAULT 'FR',
  inscrit_le timestamp NOT NULL,
  derniere_connexion timestamp,
  email_verifie boolean NOT NULL DEFAULT false,
  accepte_prospection boolean NOT NULL DEFAULT false,
  preferences jsonb,
  statut utilisateur_statut NOT NULL DEFAULT 'actif',
  CONSTRAINT uniq_utilisateur_email UNIQUE (email)
);
CREATE INDEX idx_utilisateur_inscription ON utilisateur (inscrit_le);
COMMENT ON COLUMN utilisateur.preferences IS 'Rubriques suivies, notifications';

CREATE TABLE formule_abonnement (
  id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom varchar(60) NOT NULL,
  code varchar(30) NOT NULL,
  periodicite formule_periodicite NOT NULL DEFAULT 'mensuel',
  prix numeric(6, 2) NOT NULL,
  devise char(3) NOT NULL DEFAULT 'EUR',
  jours_essai smallint NOT NULL DEFAULT 0,
  acces_archives boolean NOT NULL DEFAULT true,
  nombre_comptes smallint NOT NULL DEFAULT 1,
  description varchar(255),
  actif boolean NOT NULL DEFAULT true,
  CONSTRAINT uniq_formule_code UNIQUE (code)
);

CREATE TABLE code_promo (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(24) NOT NULL,
  libelle varchar(120),
  reduction_pourcent smallint,
  reduction_montant numeric(6, 2),
  valide_du date NOT NULL,
  valide_au date,
  utilisations_max integer,
  utilisations integer NOT NULL DEFAULT 0,
  CONSTRAINT uniq_code_promo UNIQUE (code)
);
COMMENT ON COLUMN code_promo.reduction_montant IS 'Exclusif de reduction_pourcent';

CREATE TABLE moyen_paiement (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  utilisateur_id integer NOT NULL,
  type moyen_paiement_type NOT NULL DEFAULT 'carte',
  reseau moyen_paiement_reseau,
  quatre_derniers char(4),
  titulaire varchar(100),
  expire_le date,
  iban_masque varchar(34),
  par_defaut boolean NOT NULL DEFAULT false,
  ajoute_le timestamp NOT NULL,
  CONSTRAINT fk_moyen_paiement_utilisateur FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) ON DELETE CASCADE
);
CREATE INDEX idx_moyen_paiement_utilisateur ON moyen_paiement (utilisateur_id);

CREATE TABLE abonnement (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  utilisateur_id integer NOT NULL,
  formule_id smallint NOT NULL,
  code_promo_id integer,
  moyen_paiement_id integer,
  statut abonnement_statut NOT NULL DEFAULT 'actif',
  debute_le date NOT NULL,
  prochaine_echeance date,
  resilie_le date,
  motif_resiliation varchar(160),
  renouvellement_auto boolean NOT NULL DEFAULT true,
  prix_paye numeric(6, 2) NOT NULL,
  CONSTRAINT fk_abonnement_utilisateur FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) ON DELETE CASCADE,
  CONSTRAINT fk_abonnement_formule FOREIGN KEY (formule_id) REFERENCES formule_abonnement (id),
  CONSTRAINT fk_abonnement_code_promo FOREIGN KEY (code_promo_id) REFERENCES code_promo (id),
  CONSTRAINT fk_abonnement_moyen_paiement FOREIGN KEY (moyen_paiement_id) REFERENCES moyen_paiement (id)
);
CREATE INDEX idx_abonnement_utilisateur ON abonnement (utilisateur_id);
CREATE INDEX idx_abonnement_statut ON abonnement (statut);
COMMENT ON COLUMN abonnement.prix_paye IS 'Prix réellement facturé, remise déduite';

CREATE TABLE paiement (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  abonnement_id integer NOT NULL,
  moyen_paiement_id integer,
  reference varchar(32) NOT NULL,
  numero_facture varchar(20),
  montant numeric(8, 2) NOT NULL,
  tva numeric(6, 2) NOT NULL DEFAULT 0.00,
  devise char(3) NOT NULL DEFAULT 'EUR',
  statut paiement_statut NOT NULL DEFAULT 'reussi',
  motif_echec varchar(120),
  paye_le timestamp NOT NULL,
  periode_debut date,
  periode_fin date,
  CONSTRAINT uniq_paiement_reference UNIQUE (reference),
  CONSTRAINT fk_paiement_abonnement FOREIGN KEY (abonnement_id) REFERENCES abonnement (id) ON DELETE CASCADE,
  CONSTRAINT fk_paiement_moyen FOREIGN KEY (moyen_paiement_id) REFERENCES moyen_paiement (id)
);
CREATE INDEX idx_paiement_abonnement ON paiement (abonnement_id);

CREATE TABLE remboursement (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paiement_id integer NOT NULL,
  montant numeric(8, 2) NOT NULL,
  motif remboursement_motif NOT NULL,
  commentaire varchar(255),
  rembourse_le timestamp NOT NULL,
  traite_par varchar(80),
  CONSTRAINT fk_remboursement_paiement FOREIGN KEY (paiement_id) REFERENCES paiement (id) ON DELETE CASCADE
);
CREATE INDEX idx_remboursement_paiement ON remboursement (paiement_id);

CREATE TABLE commentaire (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article_id integer NOT NULL,
  utilisateur_id integer,
  parent_id integer,
  contenu text NOT NULL,
  statut commentaire_statut NOT NULL DEFAULT 'publie',
  votes_positifs smallint NOT NULL DEFAULT 0,
  votes_negatifs smallint NOT NULL DEFAULT 0,
  poste_le timestamp NOT NULL,
  modere_le timestamp,
  modere_par integer,
  CONSTRAINT fk_commentaire_article FOREIGN KEY (article_id) REFERENCES article (id) ON DELETE CASCADE,
  CONSTRAINT fk_commentaire_utilisateur FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) ON DELETE SET NULL,
  CONSTRAINT fk_commentaire_parent FOREIGN KEY (parent_id) REFERENCES commentaire (id) ON DELETE CASCADE,
  CONSTRAINT fk_commentaire_moderateur FOREIGN KEY (modere_par) REFERENCES auteur (id)
);
CREATE INDEX idx_commentaire_article ON commentaire (article_id);
CREATE INDEX idx_commentaire_utilisateur ON commentaire (utilisateur_id);
COMMENT ON COLUMN commentaire.parent_id IS 'Réponse à un autre commentaire';

CREATE TABLE signalement_commentaire (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  commentaire_id integer NOT NULL,
  utilisateur_id integer,
  motif signalement_motif NOT NULL,
  precision_texte varchar(255),
  signale_le timestamp NOT NULL,
  traite boolean NOT NULL DEFAULT false,
  decision signalement_decision,
  CONSTRAINT fk_signalement_commentaire FOREIGN KEY (commentaire_id) REFERENCES commentaire (id) ON DELETE CASCADE,
  CONSTRAINT fk_signalement_utilisateur FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) ON DELETE SET NULL
);
CREATE INDEX idx_signalement_commentaire ON signalement_commentaire (commentaire_id);

CREATE TABLE favori (
  utilisateur_id integer NOT NULL,
  article_id integer NOT NULL,
  ajoute_le timestamp NOT NULL,
  lu boolean NOT NULL DEFAULT false,
  PRIMARY KEY (utilisateur_id, article_id),
  CONSTRAINT fk_favori_utilisateur FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) ON DELETE CASCADE,
  CONSTRAINT fk_favori_article FOREIGN KEY (article_id) REFERENCES article (id) ON DELETE CASCADE
);
CREATE INDEX idx_favori_article ON favori (article_id);

CREATE TABLE lecture (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article_id integer NOT NULL,
  utilisateur_id integer,
  lu_le timestamp NOT NULL,
  duree_secondes integer,
  pourcentage_lu smallint,
  source lecture_source NOT NULL DEFAULT 'accueil',
  appareil lecture_appareil NOT NULL DEFAULT 'mobile',
  paywall_affiche boolean NOT NULL DEFAULT false,
  CONSTRAINT fk_lecture_article FOREIGN KEY (article_id) REFERENCES article (id) ON DELETE CASCADE,
  CONSTRAINT fk_lecture_utilisateur FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) ON DELETE SET NULL
);
CREATE INDEX idx_lecture_article ON lecture (article_id);
CREATE INDEX idx_lecture_date ON lecture (lu_le);
COMMENT ON COLUMN lecture.utilisateur_id IS 'NULL pour un visiteur non connecté';

CREATE TABLE newsletter (
  id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom varchar(80) NOT NULL,
  slug varchar(80) NOT NULL,
  description varchar(255),
  periodicite newsletter_periodicite NOT NULL DEFAULT 'hebdomadaire',
  heure_envoi time NOT NULL DEFAULT '07:00:00',
  reservee_abonnes boolean NOT NULL DEFAULT false,
  CONSTRAINT uniq_newsletter_slug UNIQUE (slug)
);

CREATE TABLE inscription_newsletter (
  utilisateur_id integer NOT NULL,
  newsletter_id smallint NOT NULL,
  inscrit_le timestamp NOT NULL,
  desinscrit_le timestamp,
  origine inscription_origine NOT NULL DEFAULT 'inscription',
  PRIMARY KEY (utilisateur_id, newsletter_id),
  CONSTRAINT fk_inscription_utilisateur FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) ON DELETE CASCADE,
  CONSTRAINT fk_inscription_newsletter FOREIGN KEY (newsletter_id) REFERENCES newsletter (id) ON DELETE CASCADE
);
CREATE INDEX idx_inscription_newsletter ON inscription_newsletter (newsletter_id);

CREATE TABLE envoi_newsletter (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  newsletter_id smallint NOT NULL,
  objet varchar(160) NOT NULL,
  article_une_id integer,
  envoye_le timestamp NOT NULL,
  destinataires integer NOT NULL DEFAULT 0,
  ouvertures integer NOT NULL DEFAULT 0,
  clics integer NOT NULL DEFAULT 0,
  desinscriptions integer NOT NULL DEFAULT 0,
  CONSTRAINT fk_envoi_newsletter FOREIGN KEY (newsletter_id) REFERENCES newsletter (id) ON DELETE CASCADE,
  CONSTRAINT fk_envoi_article FOREIGN KEY (article_une_id) REFERENCES article (id) ON DELETE SET NULL
);
CREATE INDEX idx_envoi_newsletter ON envoi_newsletter (newsletter_id);

CREATE VIEW vue_article_publie AS
SELECT a.id, a.titre, a.slug, a.publie_le, a.acces, a.vues,
       concat(au.prenom, ' ', au.nom) AS auteur, c.nom AS rubrique,
       (SELECT count(*) FROM commentaire cm WHERE cm.article_id = a.id AND cm.statut = 'publie') AS commentaires
FROM article a
LEFT JOIN auteur au ON au.id = a.auteur_id
LEFT JOIN categorie c ON c.id = a.categorie_id
WHERE a.statut = 'publie';

CREATE VIEW vue_audience_mensuelle AS
SELECT to_char(l.lu_le, 'YYYY-MM') AS mois, c.nom AS rubrique,
       count(*) AS lectures, count(DISTINCT l.utilisateur_id) AS lecteurs_identifies,
       round(avg(l.duree_secondes)) AS duree_moyenne
FROM lecture l
JOIN article a ON a.id = l.article_id
LEFT JOIN categorie c ON c.id = a.categorie_id
GROUP BY mois, rubrique;
