name: Test xlarge runner

on:
  push: ~
  workflow_dispatch: ~

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest-xlarge]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: enable corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable
